"""Testi del sito Disinfestazione e Derattizzazione di Servizi Ecologici.

Si modificano qui e poi si lancia:  python3 strumenti/genera_sito_disinfestazione.py
"""

DATI = {
    "nome": "Servizi Ecologici S.r.l.",
    "marchio": "Servizi Ecologici",
    "sottotitolo": "Disinfestazione e derattizzazione",
    # Indirizzo dove verrà pubblicato il sito (da confermare: sottodominio o dominio dedicato)
    "dominio": "https://disinfestazione.serviziecologici.it",
    "sito_principale": "https://www.serviziecologici.it",
    "tel": "019 690774",
    "tel_link": "+39019690774",
    "cell": "329 591 5142",
    "verde": "800 015576",
    "verde_link": "+39800015576",
    "whatsapp": "393295915142",
    "email": "servizi@serviziecologici.it",
    "sede_op": "Via Fiume 3, 17024 Finalborgo – Finale Ligure (SV)",
    "sede_legale": "Via Fieno 3, 20123 Milano (MI)",
    "piva": "09843370157",
    "cf": "00365040096",
    "albo": "MI03807",
}

# ------------------------------------------------------------------ infestanti
# mesi: intensità da 0 (assente) a 3 (picco) da gennaio a dicembre, per il calendario stagionale
INFESTANTI = [
    {
        "slug": "topi-ratti", "nome": "Topi e ratti", "valore": "Topi e ratti", "icona": "topo",
        "breve": "Rumori nel controsoffitto, escrementi, cavi rosicchiati: derattizzazione sicura con erogatori chiusi.",
        "mesi": [2, 2, 1, 1, 1, 1, 1, 1, 2, 3, 3, 3],
        "seo_title": "Derattizzazione: eliminare topi e ratti a Savona, Imperia e Genova",
        "seo_desc": "Topi o ratti in casa, in cantina o nel locale? Derattizzazione professionale con erogatori di sicurezza, chiusura dei punti di accesso e monitoraggio. Preventivo gratuito.",
        "h1": "Topi e ratti: <em>li togliamo noi</em>, in sicurezza",
        "intro": "Un topo che vedi ne nasconde quasi sempre altri. Troviamo da dove entrano, posizioniamo esche in erogatori chiusi a cui bambini e animali non arrivano e controlliamo finché il problema è risolto.",
        "specie": [
            ("Ratto delle chiaviche (surmolotto)", "Grande e robusto, coda più corta del corpo. Vive in fognature, scarichi, cantine e piani bassi; ottimo nuotatore."),
            ("Ratto nero (dei tetti)", "Più snello, coda lunghissima, grande arrampicatore. In Liguria è comune nei sottotetti, sulle palme e lungo i muri a secco."),
            ("Topo domestico (topolino)", "Piccolo, entra da fessure di appena 6-7 mm. Si nasconde dietro elettrodomestici, mobili e nei controsoffitti."),
        ],
        "segni": [
            "Escrementi scuri a forma di chicco di riso (topi) o di oliva (ratti)",
            "Rumori di zampette o rosicchiamento di notte, soprattutto in soffitta e nel controsoffitto",
            "Cavi, tubi, sacchi e imballaggi rosicchiati",
            "Strisce scure e unte lungo muri e battiscopa, dove passano sempre",
            "Odore forte di urina in ambienti chiusi",
            "Buchi nel terreno vicino a muri e aiuole, tane sotto le siepi",
        ],
        "rischi": [
            "Trasmettono malattie come la leptospirosi e la salmonellosi, contaminando cibo e superfici",
            "Rosicchiano i cavi elettrici: è una causa nota di cortocircuiti e incendi",
            "Si riproducono molto in fretta: una coppia può dare decine di piccoli in un anno",
            "Per un'attività alimentare, la presenza di roditori significa sanzioni e chiusura",
        ],
        "intervento": [
            ("Ispezione", "Cerchiamo tracce, tane e punti di ingresso, dentro e fuori l'edificio."),
            ("Erogatori di sicurezza", "Posizioniamo esche autorizzate in contenitori chiusi a chiave, numerati e segnalati."),
            ("Chiusura degli accessi", "Ti indichiamo (o chiudiamo noi) fori, griglie e passaggi da sigillare."),
            ("Controlli", "Torniamo a verificare il consumo delle esche e rinnoviamo fino all'eliminazione."),
        ],
        "prevenzione": [
            "Tieni cibo, mangime e croccantini in contenitori chiusi",
            "Chiudi i sacchi dell'immondizia e svuota spesso i bidoni",
            "Sigilla fori attorno a tubi e cavi e metti griglie sulle bocche di aerazione",
            "Taglia l'erba alta e allontana legna e materiali accatastati dai muri",
            "Non lasciare frutta caduta in giardino",
        ],
        "faq": [
            ("Le esche sono pericolose per cani, gatti e bambini?", "Usiamo erogatori chiusi e fissati, a cui bambini e animali non possono accedere, con esche autorizzate. Ogni postazione è segnalata e registrata nella scheda di intervento."),
            ("Quanto dura una derattizzazione?", "Di solito servono più passaggi a distanza di qualche settimana, finché le esche non vengono più consumate. Per aziende e condomini proponiamo un controllo programmato tutto l'anno."),
            ("Perché non usare il veleno del supermercato?", "Messo a caso, il veleno è pericoloso per animali e bambini, i topi spesso lo evitano e muoiono in punti irraggiungibili lasciando cattivi odori. Senza chiudere gli accessi, poi, ne arrivano altri."),
        ],
    },
    {
        "slug": "blatte-scarafaggi", "nome": "Blatte e scarafaggi", "valore": "Blatte", "icona": "blatta",
        "breve": "Escono di notte da scarichi e cucine: trattamenti in gel mirati, anche in locali aperti al pubblico.",
        "mesi": [1, 1, 1, 2, 3, 3, 3, 3, 2, 1, 1, 1],
        "seo_title": "Disinfestazione blatte e scarafaggi: casa, condomini e ristoranti",
        "seo_desc": "Eliminiamo blatte e scarafaggi con gel e trattamenti mirati, senza chiudere il locale. Interventi per case, condomini, ristoranti e industrie alimentari in Liguria.",
        "h1": "Blatte e scarafaggi: <em>via per davvero</em>, non solo per qualche giorno",
        "intro": "Le blatte si nascondono nelle fessure e si riproducono in fretta: per eliminarle serve colpire i nidi, non solo gli insetti che vedi. Usiamo gel ed esche mirate che le blatte riportano nel nido.",
        "specie": [
            ("Blatta orientale", "Scura, quasi nera, lenta. Vive in luoghi umidi: scantinati, fognature, scarichi e piani terra."),
            ("Blatta germanica", "Piccola, marrone chiaro con due strisce scure. È la più diffusa in cucine, bar e ristoranti: ama il caldo degli elettrodomestici."),
            ("Blatta americana", "Grande, rossiccia, può volare. Frequente in porti, fognature, locali tecnici e cantine."),
        ],
        "segni": [
            "Insetti scuri che scappano quando accendi la luce di notte",
            "Piccoli escrementi neri simili a granelli di pepe o caffè",
            "Ooteche: capsule marroni delle uova negli angoli e dietro i mobili",
            "Odore dolciastro e sgradevole in cucina o dispensa",
            "Esuvie (pelli vuote) vicino a scarichi e battiscopa",
        ],
        "rischi": [
            "Trasportano batteri su cibo, stoviglie e superfici",
            "Possono scatenare allergie e peggiorare l'asma, soprattutto nei bambini",
            "In un ristorante una sola blatta vista da un cliente o dall'ASL è un danno enorme",
        ],
        "intervento": [
            ("Ispezione", "Troviamo i rifugi: motori di frigoriferi, scarichi, cassonetti, controsoffitti."),
            ("Gel ed esche", "Applichiamo gel professionali nei punti nascosti: nessun odore, nessuna chiusura del locale."),
            ("Trattamento dei vani tecnici", "Dove serve trattiamo scarichi, pozzetti e locali caldaie."),
            ("Monitoraggio", "Lasciamo trappole adesive di controllo e torniamo a verificare."),
        ],
        "prevenzione": [
            "Non lasciare stoviglie sporche e briciole durante la notte",
            "Chiudi bene sacchi e bidoni della spazzatura",
            "Ripara perdite d'acqua e asciuga lavelli e docce",
            "Sigilla crepe e fessure dietro mobili e battiscopa",
            "Metti tappi o retine sugli scarichi poco usati",
        ],
        "faq": [
            ("Devo uscire di casa durante il trattamento?", "Con i trattamenti in gel di solito no: il prodotto si applica in piccole gocce nei punti nascosti. Se serve un trattamento diverso ti diciamo prima cosa fare."),
            ("Perché dopo il trattamento ne vedo di più?", "Nei primi giorni le blatte escono dai rifugi perché sono disturbate o già colpite dal prodotto. È normale e dura poco."),
            ("In un condominio basta trattare un appartamento?", "Spesso no: le blatte passano dagli scarichi e dai cavedi. È più efficace trattare le parti comuni e la rete fognaria del palazzo."),
        ],
    },
    {
        "slug": "formiche", "nome": "Formiche", "valore": "Formiche", "icona": "formica",
        "breve": "File di formiche in cucina o in terrazzo: colpiamo il formicaio, non solo le operaie.",
        "mesi": [0, 0, 1, 2, 3, 3, 3, 3, 2, 1, 0, 0],
        "seo_title": "Disinfestazione formiche in casa, terrazzi e giardini",
        "seo_desc": "Formiche in cucina, sui balconi o in giardino? Trattamenti con esche che raggiungono il formicaio e la regina. Interventi in tutta la Liguria.",
        "h1": "Formiche in casa? <em>Eliminiamo il formicaio</em>",
        "intro": "Le formiche che vedi sono solo le operaie in cerca di cibo. Se non si colpisce la colonia ritornano. Usiamo esche che le operaie portano alla regina, così il formicaio si esaurisce.",
        "specie": [
            ("Formica argentina", "Piccola e scura, forma colonie enormi collegate tra loro. In Liguria è molto diffusa lungo la costa."),
            ("Formica nera dei giardini", "Fa il nido nel terreno, sotto mattonelle e nelle aiuole, ed entra in casa in cerca di zuccheri."),
            ("Formica carpentiera", "Grande, scava gallerie nel legno umido o rovinato di travi e serramenti."),
        ],
        "segni": [
            "File ordinate di formiche lungo muri, battiscopa e piani di lavoro",
            "Mucchietti di terra fine tra le mattonelle o nelle fughe",
            "Formiche alate che sciamano in primavera e in estate",
            "Segatura vicino a travi o serramenti in legno (formica carpentiera)",
        ],
        "rischi": [
            "Contaminano dispense e alimenti",
            "Alcune specie danneggiano il legno e gli impianti elettrici",
            "In negozi e ristoranti la loro presenza è una non conformità igienica",
        ],
        "intervento": [
            ("Individuazione", "Seguiamo le piste per trovare nidi e punti di ingresso."),
            ("Esche mirate", "Gel ed esche attrattive nei passaggi, che le operaie portano al nido."),
            ("Barriera esterna", "Se serve trattiamo il perimetro esterno, terrazzi e aiuole."),
        ],
        "prevenzione": [
            "Pulisci subito briciole e liquidi zuccherini",
            "Tieni zucchero, miele e marmellate in barattoli ermetici",
            "Sigilla crepe e fughe vicino a porte e finestre",
            "Non lasciare a lungo le ciotole del cibo per animali",
        ],
        "faq": [
            ("Perché gli spray non bastano?", "Lo spray uccide solo le formiche che colpisce: la colonia, con la regina, resta intatta e ne manda altre. Le esche invece arrivano fino al nido."),
            ("In quanto tempo spariscono?", "Di solito in qualche giorno o in un paio di settimane, il tempo che l'esca raggiunga tutta la colonia."),
        ],
    },
    {
        "slug": "zanzare", "nome": "Zanzare e zanzara tigre", "valore": "Zanzare", "icona": "zanzara",
        "breve": "Giardini, condomini e strutture ricettive: programma stagionale contro larve e adulti.",
        "mesi": [0, 0, 0, 1, 2, 3, 3, 3, 2, 1, 0, 0],
        "seo_title": "Disinfestazione zanzare e zanzara tigre in Liguria",
        "seo_desc": "Trattamenti larvicidi e adulticidi contro zanzare e zanzara tigre per giardini, condomini, hotel, campeggi e stabilimenti balneari. Programmi stagionali da aprile a ottobre.",
        "h1": "Zanzare e zanzara tigre: <em>torna a goderti il giardino</em>",
        "intro": "Contro le zanzare il trattamento una tantum serve a poco. Funziona un programma che colpisce le larve dove nascono, nei tombini e nei ristagni d'acqua, e riduce gli adulti nei momenti di picco.",
        "specie": [
            ("Zanzara tigre", "Nera a strisce bianche, punge anche di giorno. Depone le uova in piccoli ristagni: sottovasi, tombini, grondaie."),
            ("Zanzara comune", "Marrone, punge soprattutto di sera e di notte. Nasce in acque ferme più ampie: vasche, fossi, cisterne."),
        ],
        "segni": [
            "Punture anche di giorno, all'ombra e vicino alle piante: è la zanzara tigre",
            "Larve che si muovono in sottovasi, secchi e tombini",
            "Ronzii e punture notturne in camera da letto",
        ],
        "rischi": [
            "Punture fastidiose che rovinano giardini, terrazzi e attività all'aperto",
            "Le zanzare possono trasmettere virus come Dengue, Chikungunya e West Nile",
            "Per hotel, campeggi e ristoranti con dehors sono un danno diretto all'attività",
        ],
        "intervento": [
            ("Sopralluogo", "Mappiamo tombini, caditoie, ristagni e zone d'ombra dove si riposano gli adulti."),
            ("Larvicida", "Trattiamo tombini e caditoie ogni 3-4 settimane, da aprile a ottobre."),
            ("Adulticida", "Nei periodi di picco trattiamo siepi e vegetazione, con prodotti autorizzati e nel rispetto di api e vicini."),
            ("Consigli", "Ti lasciamo una lista dei ristagni da eliminare: è metà del risultato."),
        ],
        "prevenzione": [
            "Svuota ogni settimana sottovasi, secchi, annaffiatoi e teli che raccolgono acqua",
            "Tieni pulite grondaie e caditoie",
            "Copri cisterne e bidoni per l'acqua piovana con una zanzariera",
            "Metti pesci rossi nelle vasche ornamentali",
        ],
        "faq": [
            ("Il trattamento è pericoloso per api e animali?", "Usiamo prodotti autorizzati, scegliendo orari e zone per non colpire le piante in fiore. Ti diciamo quanto tempo tenere lontani bambini e animali dalle zone trattate."),
            ("Quanti trattamenti servono?", "Per un giardino proponiamo un programma stagionale, con passaggi ogni 3-4 settimane da primavera all'autunno. Il preventivo indica il numero esatto."),
            ("Fate anche condomini e strutture turistiche?", "Sì: condomini, hotel, campeggi, stabilimenti balneari, scuole e aree verdi. Possiamo programmare i passaggi negli orari di chiusura."),
        ],
    },
    {
        "slug": "vespe-calabroni", "nome": "Vespe e calabroni", "valore": "Vespe e calabroni", "icona": "vespa",
        "breve": "Nidi sotto il tetto, nelle tapparelle o sugli alberi, anche di Vespa velutina: rimozione sicura.",
        "mesi": [0, 0, 1, 2, 2, 3, 3, 3, 3, 2, 0, 0],
        "seo_title": "Rimozione nidi di vespe e calabroni, anche Vespa velutina, in Liguria",
        "seo_desc": "Nido di vespe o calabroni in casa, nella tapparella o su un albero? Rimozione sicura con attrezzature e protezioni professionali. Interveniamo anche sulla Vespa velutina.",
        "h1": "Nido di vespe o calabroni? <em>Non toccarlo, chiama noi</em>",
        "intro": "Vespe e calabroni difendono il nido in gruppo e possono pungere molte volte. Con tute protettive, prodotti specifici e, se serve, attrezzature per lavorare in quota, neutralizziamo e rimuoviamo il nido in sicurezza.",
        "specie": [
            ("Vespa comune e vespa cartonaia", "Nidi di carta sotto grondaie, nelle tapparelle, nei cassonetti, nel terreno o nei muri."),
            ("Calabrone europeo", "Grande, giallo e marrone. Fa il nido in cavità di alberi, sottotetti e camini."),
            ("Vespa velutina (calabrone asiatico)", "Scura con zampe gialle, specie invasiva presente nella Liguria di Ponente. Costruisce grandi nidi sferici in alto sugli alberi e attacca le api."),
        ],
        "segni": [
            "Viavai continuo di vespe sempre dallo stesso punto (tapparella, buco nel muro, grondaia)",
            "Nido di carta grigia o marrone, a forma di ombrello o di palla",
            "Ronzio dentro un muro, un cassonetto o il controsoffitto",
            "Vespe che girano attorno agli alveari (possibile Vespa velutina)",
        ],
        "rischi": [
            "Punture multiple, pericolose per chi è allergico (rischio di shock anafilattico)",
            "Attacchi improvvisi se il nido viene urtato, per esempio aprendo una tapparella o tagliando una siepe",
            "La Vespa velutina è una minaccia seria per le api e per gli apicoltori",
        ],
        "intervento": [
            ("Valutazione", "Al telefono o con un sopralluogo capiamo specie, posizione e altezza del nido."),
            ("Neutralizzazione", "Con tuta protettiva e prodotti specifici neutralizziamo la colonia, anche dentro muri e cassonetti."),
            ("Rimozione", "Quando possibile rimuoviamo il nido, anche in quota."),
            ("Controllo", "Ti diciamo come evitare che tornino a nidificare nello stesso punto."),
        ],
        "prevenzione": [
            "Controlla a fine inverno sottotetti, cassonetti e tapparelle: i nidi appena iniziati sono piccoli e facili da togliere",
            "Chiudi fori nei muri e nei cassonetti delle tapparelle",
            "Non lasciare frutta matura e bibite zuccherate all'aperto",
            "Non provare mai a bruciare o bagnare un nido: rischi punture e incendi",
        ],
        "faq": [
            ("Quanto costa rimuovere un nido di vespe?", "Dipende da dove si trova e dall'altezza: un nido nella tapparella è diverso da uno a 15 metri su un albero. Inviaci una foto su WhatsApp e ti diamo subito un'indicazione."),
            ("Vespe e calabroni muoiono da soli in inverno?", "Sì, in inverno la colonia muore e il nido viene abbandonato, ma da primavera a ottobre cresce ogni settimana. Prima si interviene, più è semplice."),
            ("Le api le togliete?", "Le api sono protette e utilissime: in caso di sciame contattiamo un apicoltore della zona per il recupero."),
        ],
    },
    {
        "slug": "cimici-dei-letti", "nome": "Cimici dei letti", "valore": "Cimici dei letti", "icona": "cimice",
        "breve": "Punture al risveglio e macchioline sul materasso: trattamenti riservati per case, hotel e B&B.",
        "mesi": [2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 2, 2],
        "seo_title": "Disinfestazione cimici dei letti per case, hotel e B&B",
        "seo_desc": "Cimici dei letti in casa, in hotel o nel B&B? Ispezione accurata e trattamenti mirati, con mezzi senza scritte per la massima riservatezza. Interventi in Liguria.",
        "h1": "Cimici dei letti: <em>interveniamo con discrezione</em>",
        "intro": "Le cimici dei letti viaggiano con valigie, mobili usati e vestiti: non sono segno di sporcizia. Sono però difficili da eliminare da soli. Facciamo un'ispezione accurata e un trattamento in più passaggi, con la massima riservatezza.",
        "specie": [
            ("Cimice dei letti (Cimex lectularius)", "Piatta, ovale, color ruggine, lunga circa 5 mm. Di giorno si nasconde nelle cuciture del materasso, nella testiera, nei battiscopa e nelle prese."),
        ],
        "segni": [
            "Punture al risveglio, spesso in fila o a gruppi di tre, su braccia, collo e gambe",
            "Piccole macchie nere o rossastre su lenzuola e materasso",
            "Insetti piatti color ruggine nelle cuciture del materasso o nella testiera",
            "Odore dolciastro nelle infestazioni più forti",
        ],
        "rischi": [
            "Prurito, insonnia e forte disagio, specie nei bambini",
            "Si diffondono facilmente ad altre stanze e appartamenti",
            "Per hotel e B&B una sola recensione negativa può costare molte prenotazioni",
        ],
        "intervento": [
            ("Ispezione", "Controlliamo letti, divani, mobili e stanze vicine per capire quanto è estesa l'infestazione."),
            ("Preparazione", "Ti diamo una lista semplice: cosa lavare a 60 °C, cosa chiudere nei sacchi, cosa spostare."),
            ("Trattamento", "Trattiamo cuciture, fessure, testiere e battiscopa con prodotti specifici."),
            ("Secondo passaggio", "Torniamo dopo circa due settimane per colpire le cimici nate dalle uova."),
        ],
        "prevenzione": [
            "In viaggio appoggia la valigia sul portabagagli, non sul letto",
            "Al rientro lava i vestiti ad alta temperatura",
            "Controlla bene mobili, materassi e divani usati prima di portarli in casa",
            "In hotel e B&B forma il personale ai controlli durante il cambio biancheria",
        ],
        "faq": [
            ("Devo buttare il materasso?", "Quasi mai. Nella maggior parte dei casi il materasso si tratta e si protegge con una fodera anti-cimici. Te lo diciamo dopo l'ispezione."),
            ("Arrivate con furgoni riconoscibili?", "Per hotel, B&B e privati che lo chiedono interveniamo con la massima discrezione, anche in orari concordati."),
        ],
    },
    {
        "slug": "pulci-zecche", "nome": "Pulci e zecche", "valore": "Pulci e zecche", "icona": "zecca",
        "breve": "Punture alle caviglie, animali che si grattano, giardini infestati: trattamenti interni ed esterni.",
        "mesi": [0, 0, 1, 2, 3, 3, 3, 3, 2, 1, 0, 0],
        "seo_title": "Disinfestazione pulci e zecche in casa e in giardino",
        "seo_desc": "Pulci in casa o zecche in giardino? Trattamenti mirati per abitazioni, giardini, canili, maneggi e aree verdi. Interventi in Liguria.",
        "h1": "Pulci e zecche: <em>proteggi la tua famiglia e i tuoi animali</em>",
        "intro": "Le pulci si nascondono in tappeti, cucce e divani; le zecche nell'erba alta e tra i cespugli. Trattiamo casa e giardino insieme, mentre il veterinario si occupa degli animali.",
        "specie": [
            ("Pulce del gatto e del cane", "Piccolissima e saltatrice. Uova e larve si nascondono in tappeti, cucce, divani e fessure del pavimento."),
            ("Zecche", "Aspettano nell'erba alta, nei cespugli e nei boschi e si attaccano a persone e animali di passaggio."),
        ],
        "segni": [
            "Punture rosse e pruriginose alle caviglie e sulle gambe",
            "Cane o gatto che si gratta in continuazione",
            "Puntini neri nel pelo o nella cuccia",
            "Zecche trovate sugli animali dopo una passeggiata in giardino",
        ],
        "rischi": [
            "Prurito e reazioni allergiche",
            "Le zecche possono trasmettere malattie come la malattia di Lyme",
            "Le pulci possono infestare un appartamento vuoto per mesi",
        ],
        "intervento": [
            ("Ispezione", "Individuiamo dove vivono le larve: cucce, tappeti, divani, aree esterne."),
            ("Trattamento interno", "Trattiamo pavimenti, tappeti e fessure con prodotti che bloccano anche lo sviluppo delle larve."),
            ("Trattamento esterno", "In giardino trattiamo erba, siepi e zone d'ombra frequentate dagli animali."),
        ],
        "prevenzione": [
            "Tratta cani e gatti con gli antiparassitari consigliati dal veterinario",
            "Lava spesso cucce e copertine ad alta temperatura",
            "Passa l'aspirapolvere su tappeti e divani e svuota subito il sacchetto",
            "Tieni l'erba del giardino bassa",
        ],
        "faq": [
            ("Devo trattare anche l'animale?", "Sì: il trattamento dell'animale lo decide il veterinario. Noi ci occupiamo dell'ambiente: da soli i due interventi non bastano."),
            ("Perché ci sono pulci in una casa vuota?", "Le pulci possono restare a lungo allo stadio di bozzolo e si risvegliano quando qualcuno rientra in casa. Succede spesso dopo un trasloco."),
        ],
    },
    {
        "slug": "mosche", "nome": "Mosche e insetti volanti", "valore": "Mosche", "icona": "mosca",
        "breve": "Cucine professionali, stalle e locali rifiuti: lampade cattura-insetti e trattamenti mirati.",
        "mesi": [0, 0, 1, 1, 2, 3, 3, 3, 2, 1, 0, 0],
        "seo_title": "Controllo mosche e insetti volanti per ristoranti e aziende alimentari",
        "seo_desc": "Lampade cattura-insetti, trattamenti larvicidi e monitoraggio contro mosche e insetti volanti per cucine, industrie alimentari, aziende agricole e locali rifiuti.",
        "h1": "Mosche e insetti volanti: <em>fuori dalla tua cucina</em>",
        "intro": "Nelle attività alimentari le mosche sono uno dei primi rischi controllati dall'ASL. Mettiamo insieme prevenzione, lampade cattura-insetti a piastra collante e trattamenti dei punti in cui si sviluppano le larve.",
        "specie": [
            ("Mosca domestica", "Si sviluppa in rifiuti organici, letame e residui di cibo; si posa su tutto, alimenti compresi."),
            ("Moscerini della frutta e dei tombini", "Piccolissimi, nascono nella frutta matura, negli scarichi e nei sifoni sporchi."),
        ],
        "segni": [
            "Tante mosche in cucina, vicino ai rifiuti o alle zone di carico",
            "Nuvolette di moscerini vicino a scarichi, lavelli o frutta",
            "Larve nei bidoni dell'organico o nei pozzetti",
        ],
        "rischi": [
            "Trasportano batteri dai rifiuti agli alimenti",
            "Sono una non conformità HACCP nei controlli ufficiali",
            "Danno un'immagine di scarsa igiene a clienti e ospiti",
        ],
        "intervento": [
            ("Analisi dei focolai", "Troviamo dove nascono: rifiuti, scarichi, sifoni, letamai."),
            ("Lampade cattura-insetti", "Installiamo lampade a piastra collante, adatte alle zone di preparazione degli alimenti."),
            ("Trattamenti", "Trattiamo i focolai con larvicidi e, se serve, le superfici esterne."),
            ("Manutenzione", "Sostituiamo periodicamente piastre e lampade e registriamo le catture."),
        ],
        "prevenzione": [
            "Svuota e lava spesso i bidoni dell'organico",
            "Metti zanzariere su finestre e porte di servizio",
            "Pulisci sifoni e scarichi dei lavelli con regolarità",
            "Non tenere frutta troppo matura all'aperto",
        ],
        "faq": [
            ("Che lampade usate in cucina?", "Nelle zone alimentari usiamo lampade a piastra collante, che trattengono gli insetti senza disperdere frammenti come succede con le lampade a scarica elettrica."),
            ("Ogni quanto si cambiano le piastre?", "Di solito ogni 1-2 mesi, più spesso in estate. Nei contratti HACCP lo facciamo noi durante i passaggi programmati."),
        ],
    },
    {
        "slug": "piccioni-gabbiani", "nome": "Piccioni e gabbiani", "valore": "Piccioni e gabbiani", "icona": "uccello",
        "breve": "Guano su terrazzi, tetti e insegne: reti, dissuasori e pulizia, senza far male agli animali.",
        "mesi": [2, 2, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2],
        "seo_title": "Allontanamento piccioni, gabbiani, storni e pipistrelli: reti, dissuasori e pulizia guano",
        "seo_desc": "Allontaniamo piccioni e gabbiani da tetti, terrazzi, cortili e capannoni con reti, dissuasori ad aghi e cavi tesi, sistemi incruenti. Pulizia e sanificazione del guano.",
        "h1": "Piccioni e gabbiani: <em>allontanati con metodi incruenti</em>",
        "intro": "Il guano rovina facciate, grondaie e impianti, e porta parassiti e malattie. Puliamo e sanifichiamo, poi installiamo sistemi che impediscono agli uccelli di posarsi e nidificare, senza far loro del male.",
        "specie": [
            ("Piccione di città", "Nidifica su cornicioni, sottotetti, travi dei capannoni e terrazzi in disuso."),
            ("Gabbiano reale", "Sempre più presente nelle città liguri: nidifica sui tetti piani ed è aggressivo nel periodo dei piccoli."),
            ("Storni, colombi e corvi", "Si radunano in grandi gruppi su alberi, tetti e capannoni, sporcando cortili, auto e piazzali."),
            ("Pipistrelli", "Si rifugiano in sottotetti e cassonetti. Sono specie protette: si allontanano solo con metodi rispettosi, chiudendo i passaggi quando sono usciti."),
        ],
        "segni": [
            "Guano su davanzali, terrazzi, auto e insegne",
            "Nidi sotto tegole, su cornicioni, condizionatori e travi",
            "Rumori sul tetto all'alba e gabbiani che attaccano in primavera",
            "Grondaie intasate da piume e guano",
        ],
        "rischi": [
            "Il guano è corrosivo per pietra, metalli e impermeabilizzazioni",
            "Porta acari, zecche dei piccioni e batteri",
            "Nidi nelle grondaie causano infiltrazioni d'acqua",
            "Nelle aziende alimentari il guano è un grave rischio igienico",
        ],
        "intervento": [
            ("Sopralluogo", "Studiamo i punti di sosta e di nidificazione e scegliamo la soluzione giusta per l'edificio."),
            ("Pulizia e sanificazione", "Rimuoviamo guano e nidi e sanifichiamo le superfici."),
            ("Dissuasori", "Installiamo reti, aghi in policarbonato o acciaio, cavi tesi, dissuasori a ultrasuoni e centraline anti-volatili."),
            ("Verifica", "Controlliamo nel tempo che i sistemi restino efficaci."),
        ],
        "prevenzione": [
            "Non dare da mangiare a piccioni e gabbiani",
            "Chiudi i bidoni e non lasciare avanzi su terrazzi e dehors",
            "Chiudi con una rete i sottotetti e le aperture",
        ],
        "faq": [
            ("I dissuasori fanno male agli uccelli?", "No: aghi, reti e cavi impediscono solo di posarsi e nidificare. Sono sistemi incruenti, rispettosi degli animali."),
            ("Si possono togliere i nidi di gabbiano?", "I gabbiani sono specie protette: si interviene prima della nidificazione, con dissuasori e reti. Ti spieghiamo cosa si può fare e quando."),
        ],
    },
    {
        "slug": "processionaria", "nome": "Processionaria", "valore": "Processionaria", "icona": "bruco",
        "breve": "Nidi bianchi sui pini e bruchi in fila: pericolosi per cani e bambini. Rimozione e trattamenti.",
        "mesi": [2, 3, 3, 2, 0, 0, 0, 0, 1, 1, 2, 2],
        "seo_title": "Processionaria del pino: rimozione nidi e trattamenti in Liguria",
        "seo_desc": "Nidi di processionaria sui pini del giardino o del condominio? Rimozione dei nidi e trattamenti preventivi. I peli urticanti sono pericolosi per cani e bambini.",
        "h1": "Processionaria: <em>proteggi bambini e animali</em>",
        "intro": "In Liguria i pini sono ovunque, e con loro la processionaria. I bruchi hanno peli urticanti molto pericolosi per cani, gatti e bambini. Rimuoviamo i nidi e programmiamo trattamenti nel momento giusto dell'anno.",
        "specie": [
            ("Processionaria del pino", "Bruco peloso che vive in nidi bianchi e sericei sulle cime dei pini; a fine inverno scende a terra in lunghe file."),
        ],
        "segni": [
            "Nidi bianchi, simili a batuffoli di ovatta, sulle punte dei rami di pini e cedri",
            "File di bruchi pelosi che camminano a terra in fine inverno o primavera",
            "Aghi di pino rosicchiati e rami spogli",
        ],
        "rischi": [
            "I peli urticanti causano forti irritazioni a pelle, occhi e vie respiratorie",
            "Nei cani il contatto con la bocca può provocare gravi lesioni alla lingua: serve subito il veterinario",
            "Le piante colpite si indeboliscono anno dopo anno",
        ],
        "intervento": [
            ("Ispezione delle piante", "Contiamo e mappiamo i nidi su pini e cedri."),
            ("Rimozione dei nidi", "In inverno tagliamo e distruggiamo i nidi in sicurezza, anche in quota."),
            ("Trattamento preventivo", "Tra fine estate e autunno trattiamo le chiome per colpire le larve giovani."),
            ("Trappole", "Dove utile installiamo trappole a collare sul tronco per catturare i bruchi in discesa."),
        ],
        "prevenzione": [
            "Controlla i pini a fine autunno e in inverno, quando i nidi si vedono bene",
            "Non toccare mai nidi e bruchi, nemmeno con un bastone",
            "In primavera tieni cani e bambini lontani dalla base dei pini",
        ],
        "faq": [
            ("Quando è il momento giusto per intervenire?", "I nidi si rimuovono in inverno; i trattamenti preventivi si fanno tra fine estate e autunno. Se ci chiami ora ti proponiamo il calendario giusto."),
            ("Cosa faccio se il cane tocca un bruco?", "Non strofinare la zona e porta subito il cane dal veterinario: è un'emergenza."),
        ],
    },
    {
        "slug": "insetti-derrate", "nome": "Tarme e insetti delle derrate", "valore": "Insetti delle derrate", "icona": "barattolo",
        "breve": "Farine, pasta e cereali con piccoli insetti o ragnatele: monitoraggio a feromoni e trattamenti.",
        "mesi": [1, 1, 1, 2, 2, 3, 3, 3, 2, 1, 1, 1],
        "seo_title": "Tarme alimentari e insetti delle derrate: disinfestazione per magazzini e panifici",
        "seo_desc": "Tarme della farina, punteruoli e insetti delle derrate in dispensa, panifici, pastifici e magazzini alimentari. Monitoraggio con trappole a feromoni e trattamenti mirati.",
        "h1": "Tarme e insetti delle derrate: <em>dispense e magazzini puliti</em>",
        "intro": "Farfalline nella dispensa, ragnatele nella farina, piccoli coleotteri nei cereali: sono gli insetti delle derrate. Per panifici, pastifici e magazzini alimentari usiamo trappole a feromoni per controllarli prima che diventino un problema.",
        "specie": [
            ("Tignola o tarma della farina", "Piccola farfallina grigia; le larve tessono ragnatele in farine, frutta secca e cereali."),
            ("Punteruoli e tribolio", "Piccoli coleotteri scuri che attaccano riso, pasta, farine e granaglie."),
            ("Tarme dei vestiti", "Le larve rovinano lana, seta e tessuti naturali in armadi e magazzini."),
        ],
        "segni": [
            "Farfalline che volano in cucina o in dispensa la sera",
            "Ragnatele e grumi nella farina, nella pasta o nei cereali",
            "Piccoli fori nelle confezioni",
            "Buchi in maglioni e tessuti di lana",
        ],
        "rischi": [
            "Grandi quantità di alimenti da buttare",
            "Reclami dei clienti e richiami dei prodotti",
            "Non conformità nelle verifiche dei clienti della grande distribuzione",
        ],
        "intervento": [
            ("Ispezione", "Controlliamo scaffali, silos, macchinari e materie prime per trovare i focolai."),
            ("Trappole a feromoni", "Installiamo trappole che attirano e catturano i maschi e ci dicono dove si concentra il problema."),
            ("Trattamenti", "Trattiamo locali e macchinari con prodotti adatti agli ambienti alimentari."),
            ("Report", "Registriamo le catture e ti diamo i dati per HACCP e audit."),
        ],
        "prevenzione": [
            "Conserva farine e cereali in barattoli ermetici",
            "Applica la regola: il primo prodotto che entra è il primo che esce",
            "Controlla le merci in arrivo e scarta le confezioni rovinate",
            "Pulisci a fondo scaffali e macchinari, anche negli angoli",
        ],
        "faq": [
            ("In casa basta buttare la farina?", "Butta i prodotti infestati e pulisci bene gli scaffali. Se le farfalline continuano, il focolaio è altrove: possiamo aiutarti a trovarlo."),
            ("Le trappole a feromoni sono sicure?", "Sì, non contengono insetticidi: attirano gli insetti con un odore specifico e li trattengono con la colla."),
        ],
    },
    {
        "slug": "pesciolini-argento", "nome": "Pesciolini d'argento e altri insetti", "valore": "Altri insetti", "icona": "pesciolino",
        "breve": "Pesciolini d'argento, ragni, millepiedi, cimici asiatiche: ti diciamo cosa sono e come eliminarli.",
        "mesi": [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        "seo_title": "Pesciolini d'argento, ragni, millepiedi e cimici asiatiche: disinfestazione",
        "seo_desc": "Pesciolini d'argento in bagno, ragni, millepiedi, cimici asiatiche e altri insetti in casa? Riconoscimento e trattamenti mirati in tutta la Liguria.",
        "h1": "Pesciolini d'argento e altri insetti: <em>capiamo cos'è e lo risolviamo</em>",
        "intro": "Non sai che insetto è? Mandaci una foto su WhatsApp: lo riconosciamo e ti diciamo se serve un intervento o se bastano pochi accorgimenti.",
        "specie": [
            ("Pesciolino d'argento", "Insetto argentato e veloce che ama i luoghi umidi: bagni, cantine, dietro le piastrelle. Rovina carta e cartone."),
            ("Cimice asiatica", "Marrone e a forma di scudo, in autunno entra in casa in gran numero per svernare."),
            ("Ragni e millepiedi", "Di solito innocui, ma in gran numero indicano umidità o la presenza di altri insetti."),
        ],
        "segni": [
            "Insetti argentati che scappano accendendo la luce in bagno",
            "Carta da parati, libri e scatoloni rosicchiati",
            "Cimici che si radunano su finestre e cassonetti in autunno",
        ],
        "rischi": [
            "Danni a carta, archivi, libri e tessuti",
            "Disagio e fastidio, soprattutto nelle strutture ricettive",
        ],
        "intervento": [
            ("Riconoscimento", "Identifichiamo l'insetto, anche da una foto."),
            ("Cause", "Troviamo cosa lo attira: umidità, crepe, luci, alimenti."),
            ("Trattamento mirato", "Se serve trattiamo i punti di rifugio con prodotti specifici."),
        ],
        "prevenzione": [
            "Arieggia e deumidifica bagni e cantine",
            "Sigilla fughe e crepe di piastrelle e battiscopa",
            "Metti zanzariere fini su finestre e cassonetti",
        ],
        "faq": [
            ("Posso mandarvi una foto dell'insetto?", "Certo: scrivici su WhatsApp con una foto e il comune in cui ti trovi. Ti rispondiamo con un consiglio e, se serve, con un preventivo."),
        ],
    },
]

# ------------------------------------------------------------------ servizi
SERVIZI = [
    {
        "slug": "derattizzazione", "nome": "Derattizzazione", "icona": "erogatore", "valore": "Topi e ratti",
        "breve": "Erogatori di sicurezza, chiusura degli accessi e controlli periodici contro topi e ratti.",
        "seo_title": "Derattizzazione professionale per case, condomini e aziende",
        "seo_desc": "Derattizzazione con erogatori di sicurezza numerati, planimetria delle postazioni, chiusura degli accessi e controlli periodici. Per privati, condomini e attività alimentari.",
        "h1": "Derattizzazione <em>sicura e documentata</em>",
        "intro": "Un servizio completo contro topi e ratti: dall'ispezione alla chiusura dei passaggi, fino ai controlli periodici con report. Ideale per condomini, aziende e attività alimentari.",
        "cosa": [
            "<strong>Ispezione</strong> di locali, cantine, cortili, fognature e perimetro esterno",
            "<strong>Erogatori di sicurezza</strong> chiusi a chiave, fissati e numerati",
            "<strong>Planimetria delle postazioni</strong> per HACCP e controlli ASL",
            "<strong>Trappole meccaniche</strong> dove le esche non sono adatte, per esempio nelle zone di lavorazione alimenti",
            "<strong>Proofing</strong>: chiusura di fori, griglie e passaggi",
            "<strong>Controlli periodici</strong> con sostituzione delle esche e report",
        ],
        "per_chi": ["Case e ville", "Condomini", "Ristoranti, bar e negozi alimentari", "Industrie e magazzini", "Porti, cantieri navali e aziende agricole"],
        "documenti": ["Scheda di intervento con prodotti e dosi", "Planimetria con postazioni numerate", "Report dei controlli e dei consumi", "Schede tecniche e di sicurezza dei prodotti"],
        "faq": [
            ("Ogni quanto si fanno i controlli?", "Dipende dal rischio: per un condominio di solito bastano alcuni passaggi l'anno, per un'attività alimentare i controlli sono più frequenti. Lo concordiamo nel contratto."),
        ],
    },
    {
        "slug": "disinfestazione-insetti", "nome": "Disinfestazione da insetti", "icona": "spruzzino", "valore": "Blatte",
        "breve": "Blatte, formiche, pulci, cimici e altri insetti striscianti: gel, esche e trattamenti mirati.",
        "seo_title": "Disinfestazione da insetti striscianti e volanti",
        "seo_desc": "Disinfestazione da blatte, formiche, cimici dei letti, pulci, zecche e altri insetti. Trattamenti mirati e a basso impatto per abitazioni, condomini e aziende.",
        "h1": "Disinfestazione da insetti, <em>mirata e a basso impatto</em>",
        "intro": "Scegliamo il trattamento in base all'insetto e al luogo: gel ed esche nelle cucine, trattamenti localizzati nei vani tecnici, trappole di monitoraggio per controllare il risultato.",
        "cosa": [
            "Trattamenti con <strong>gel ed esche</strong> per blatte e formiche, senza chiudere il locale",
            "Trattamenti <strong>localizzati</strong> su fessure, scarichi, pozzetti e vani tecnici",
            "Interventi contro <strong>cimici dei letti, pulci e zecche</strong>",
            "<strong>Trappole di monitoraggio</strong> per verificare il risultato nel tempo",
            "<strong>Consigli</strong> scritti per evitare che il problema ritorni",
        ],
        "per_chi": ["Privati", "Condomini", "Ristoranti, bar e mense", "Hotel e B&B", "Scuole, uffici e negozi"],
        "documenti": ["Scheda di intervento", "Schede tecniche e di sicurezza dei prodotti", "Indicazioni su come comportarsi dopo il trattamento"],
        "faq": [
            ("I prodotti hanno odore?", "Gel ed esche non hanno odore e si applicano in piccole quantità in punti nascosti. Per i trattamenti diversi ti diciamo prima quanto tempo arieggiare."),
        ],
    },
    {
        "slug": "disinfestazione-zanzare", "nome": "Programma antizanzare", "icona": "zanzara", "valore": "Zanzare",
        "breve": "Ciclo stagionale da aprile a ottobre con larvicidi nei tombini e trattamenti adulticidi.",
        "seo_title": "Programma antizanzare stagionale per giardini, condomini e strutture turistiche",
        "seo_desc": "Programma stagionale contro zanzara tigre e zanzara comune: larvicidi nei tombini, adulticidi nei periodi di picco, calendario da aprile a ottobre.",
        "h1": "Programma antizanzare: <em>un'estate più tranquilla</em>",
        "intro": "Un calendario di interventi da primavera all'autunno, pensato per giardini privati, condomini, hotel, campeggi, stabilimenti balneari e aree verdi.",
        "cosa": [
            "<strong>Mappatura</strong> dei focolai: tombini, caditoie, ristagni",
            "<strong>Larvicida</strong> nei tombini ogni 3-4 settimane",
            "<strong>Adulticida</strong> sulla vegetazione nei periodi di picco",
            "Interventi <strong>prima di eventi</strong> all'aperto: matrimoni, feste, serate",
            "<strong>Promemoria</strong>: ti avvisiamo prima di ogni passaggio",
        ],
        "per_chi": ["Ville e giardini", "Condomini con aree verdi", "Hotel, campeggi e agriturismi", "Stabilimenti balneari", "Scuole e parchi"],
        "documenti": ["Calendario dei passaggi", "Scheda di ogni intervento", "Avvisi per condomini e ospiti"],
        "faq": [
            ("Potete trattare prima di un evento?", "Sì: per matrimoni, feste e serate all'aperto facciamo un trattamento mirato il giorno prima o il giorno stesso."),
        ],
    },
    {
        "slug": "rimozione-nidi-vespe-calabroni", "nome": "Rimozione nidi di vespe e calabroni", "icona": "vespa", "valore": "Vespe e calabroni",
        "breve": "Intervento rapido e in sicurezza, anche in quota e sulla Vespa velutina.",
        "seo_title": "Rimozione nidi di vespe e calabroni: intervento rapido in Liguria",
        "seo_desc": "Nido di vespe, calabroni o Vespa velutina? Neutralizzazione e rimozione in sicurezza, anche in quota, in tapparelle, cassonetti, sottotetti e alberi.",
        "h1": "Rimozione nidi di vespe e calabroni, <em>senza rischi</em>",
        "intro": "Mandaci una foto del nido su WhatsApp: ti diciamo subito di che specie si tratta e organizziamo l'intervento il prima possibile.",
        "cosa": [
            "Neutralizzazione di nidi in <strong>tapparelle, cassonetti, grondaie e muri</strong>",
            "Nidi nel <strong>terreno</strong>, nelle siepi e nelle cavità",
            "Nidi <strong>in quota</strong> su alberi e sottotetti",
            "Interventi su <strong>Vespa velutina</strong> (calabrone asiatico)",
            "Consigli per evitare nuove nidificazioni",
        ],
        "per_chi": ["Privati", "Condomini", "Scuole e asili", "Stabilimenti balneari e campeggi", "Apicoltori e aziende agricole"],
        "documenti": ["Scheda di intervento"],
        "faq": [
            ("Fate interventi urgenti?", "Sì: quando il nido è vicino a porte, finestre, scuole o persone allergiche diamo la priorità. Chiamaci allo 019 690774."),
        ],
    },
    {
        "slug": "allontanamento-volatili", "nome": "Allontanamento volatili", "icona": "uccello", "valore": "Piccioni e gabbiani",
        "breve": "Reti, aghi dissuasori, cavi tesi e pulizia del guano per piccioni e gabbiani.",
        "seo_title": "Allontanamento piccioni e gabbiani: reti, dissuasori, pulizia guano",
        "seo_desc": "Sistemi incruenti contro piccioni e gabbiani: reti, aghi dissuasori, cavi tesi, pulizia e sanificazione del guano per condomini, capannoni e attività.",
        "h1": "Allontanamento volatili, <em>con sistemi incruenti</em>",
        "intro": "Studiamo l'edificio e installiamo la protezione più adatta, discreta e duratura. Prima puliamo e sanifichiamo le superfici sporche di guano.",
        "cosa": [
            "<strong>Pulizia e sanificazione</strong> di guano e nidi",
            "<strong>Reti</strong> anti-volatile per cortili, cavedi, sottotetti e capannoni",
            "<strong>Aghi dissuasori</strong> su davanzali, cornicioni, insegne e travi",
            "<strong>Cavi tesi</strong> poco visibili su parapetti e colmi",
            "<strong>Dissuasori a ultrasuoni</strong> e <strong>centraline anti-volatili</strong>",
            "Allontanamento di <strong>storni, colombi, corvi e pipistrelli</strong>, nel rispetto delle specie protette",
            "<strong>Disinfestazione</strong> da acari e zecche dei piccioni",
        ],
        "per_chi": ["Condomini", "Capannoni e magazzini", "Chiese ed edifici storici", "Ristoranti e dehors", "Porti e stabilimenti"],
        "documenti": ["Relazione del sopralluogo", "Scheda di intervento"],
        "faq": [
            ("Serve il permesso del condominio?", "Per installare reti e dissuasori sulle parti comuni di solito sì. Ti prepariamo un preventivo chiaro da portare in assemblea."),
        ],
    },
    {
        "slug": "sanificazione-disinfezione", "nome": "Sanificazione e disinfezione", "icona": "scudo", "valore": "Sanificazione",
        "breve": "Disinfezione di ambienti, impianti e superfici dopo infestazioni, allagamenti o su richiesta.",
        "seo_title": "Sanificazione e disinfezione di ambienti per case, uffici e aziende",
        "seo_desc": "Sanificazione e disinfezione professionale di locali, uffici, mezzi, cantine e ambienti dopo infestazioni o allagamenti. Prodotti autorizzati e certificato di intervento.",
        "h1": "Sanificazione e disinfezione <em>degli ambienti</em>",
        "intro": "Dopo un'infestazione, un allagamento o lo sgombero di un locale, una sanificazione professionale riporta gli ambienti in condizioni igieniche sicure.",
        "cosa": [
            "<strong>Disinfezione</strong> di superfici e ambienti con prodotti autorizzati",
            "Sanificazione <strong>dopo infestazioni</strong> di roditori o volatili",
            "Sanificazione di <strong>cantine e locali</strong> dopo allagamenti o sgomberi",
            "Trattamenti di <strong>uffici, spogliatoi, mezzi</strong> e locali comuni",
            "<strong>Sanificazione delle tubazioni</strong> (acque bianche, nere e grigie) e <strong>controllo del rischio Legionella</strong>",
            "<strong>Igienizzazione degli impianti di condizionamento</strong> e dei canali d'aria",
            "Coordinamento con gli altri servizi di Servizi Ecologici: <strong>spurghi, pulizia cappe, pulizia serbatoi e relining delle tubazioni</strong>",
        ],
        "per_chi": ["Privati", "Condomini", "Uffici e aziende", "Scuole e palestre", "Strutture sanitarie e RSA"],
        "documenti": ["Certificato di avvenuta sanificazione", "Schede tecniche e di sicurezza dei prodotti"],
        "faq": [
            ("Rilasciate un certificato?", "Sì, al termine dell'intervento rilasciamo il certificato con data, ambienti trattati e prodotti utilizzati."),
        ],
    },
    {
        "slug": "monitoraggio-haccp", "nome": "Pest control HACCP", "icona": "registro", "valore": "Contratto HACCP",
        "breve": "Piano di monitoraggio con postazioni numerate, lampade, report e documenti pronti per l'ASL.",
        "seo_title": "Pest control HACCP per ristoranti e industrie alimentari",
        "seo_desc": "Piano di monitoraggio infestanti HACCP: postazioni numerate su planimetria, lampade cattura-insetti, controlli periodici, registro e report pronti per ASL e audit.",
        "h1": "Pest control HACCP: <em>documenti sempre pronti</em> per l'ASL",
        "intro": "Il Regolamento CE 852/2004 chiede a chi tratta alimenti di controllare gli infestanti. Ti diamo un piano completo, con controlli periodici e una cartella sempre aggiornata da mostrare a ispettori e clienti.",
        "cosa": [
            "<strong>Valutazione dei rischi</strong> iniziale del locale o dello stabilimento",
            "<strong>Planimetria</strong> con postazioni numerate per roditori, striscianti e volanti",
            "<strong>Lampade cattura-insetti</strong> a piastra collante",
            "<strong>Trappole a feromoni</strong> per gli insetti delle derrate",
            "<strong>Controlli periodici</strong> programmati, con azioni correttive",
            "<strong>Report e trend</strong> delle catture, utili anche per gli audit dei clienti",
            "<strong>Interventi extra</strong> su chiamata quando serve",
        ],
        "per_chi": ["Ristoranti, pizzerie e bar", "Mense e cucine centralizzate", "Panifici, pasticcerie e pastifici", "Industrie alimentari e magazzini", "Supermercati e negozi alimentari"],
        "documenti": ["Piano di monitoraggio e valutazione dei rischi", "Planimetria delle postazioni", "Schede di ogni controllo", "Schede tecniche e di sicurezza dei prodotti", "Report periodici"],
        "faq": [
            ("Il pest control è obbligatorio?", "Chi produce, trasforma, conserva o somministra alimenti deve prevenire e controllare gli infestanti, e dimostrarlo con i documenti nel piano HACCP. Con il nostro servizio hai tutto pronto."),
            ("Fate i controlli fuori dall'orario di apertura?", "Sì, li programmiamo negli orari che non disturbano il servizio."),
        ],
    },
]

# ------------------------------------------------------------------ settori
SETTORI = [
    {
        "slug": "casa-privati", "nome": "Casa e privati", "icona": "casa",
        "breve": "Topi in cantina, vespe nella tapparella, zanzare in giardino: interveniamo a casa tua.",
        "seo_title": "Disinfestazione e derattizzazione per la casa",
        "seo_desc": "Disinfestazione per privati: topi, blatte, formiche, vespe, zanzare, cimici e pulci. Sopralluogo, preventivo gratuito e prodotti sicuri per bambini e animali.",
        "h1": "Disinfestazione per la casa, <em>sicura per tutta la famiglia</em>",
        "intro": "Sappiamo che a casa ci sono bambini, animali e un orto. Scegliamo prodotti e metodi adatti e ti spieghiamo tutto prima di iniziare.",
        "problemi": ["Topi e ratti in cantina, in soffitta o in giardino", "Blatte e formiche in cucina", "Vespe e calabroni nelle tapparelle o sotto il tetto", "Zanzare in giardino e sul terrazzo", "Cimici dei letti dopo un viaggio", "Pulci dopo un trasloco o per colpa degli animali"],
        "soluzioni": ["Sopralluogo e preventivo gratuiti", "Trattamenti mirati e a basso impatto", "Erogatori chiusi, sicuri per bambini e animali", "Consigli scritti di prevenzione", "Programma antizanzare per il giardino"],
        "documenti": ["Scheda di intervento con prodotti e indicazioni"],
        "faq": [("Devo esserci durante l'intervento?", "Per i trattamenti in casa sì, o almeno qualcuno che ci apra. Concordiamo con te giorno e orario.")],
    },
    {
        "slug": "condomini", "nome": "Condomini e amministratori", "icona": "palazzo",
        "breve": "Contratti annuali con passaggi programmati e un report pronto per l'assemblea.",
        "seo_title": "Derattizzazione e disinfestazione per condomini",
        "seo_desc": "Contratti annuali di derattizzazione e disinfestazione per condomini: passaggi programmati, avvisi per i condòmini, report per l'amministratore e l'assemblea.",
        "h1": "Condomini: <em>un contratto, zero pensieri</em>",
        "intro": "Per gli amministratori prepariamo contratti annuali di derattizzazione e disinfestazione delle parti comuni, con passaggi programmati e documenti chiari.",
        "problemi": ["Ratti in cortili, cantine e locali rifiuti", "Blatte che risalgono dagli scarichi condominiali", "Piccioni e gabbiani su tetti e cornicioni", "Zanzare nelle aree verdi e nei tombini", "Lamentele dei condòmini e richieste all'amministratore"],
        "soluzioni": ["Derattizzazione e disinfestazione con passaggi programmati nell'anno", "Avvisi da appendere in bacheca prima di ogni passaggio", "Interventi extra su chiamata dei condòmini", "Report annuale per l'assemblea", "Un solo referente anche per spurghi, colonne di scarico e rifiuti"],
        "documenti": ["Contratto con calendario dei passaggi", "Schede di intervento", "Planimetria delle postazioni", "Report annuale"],
        "faq": [("Potete trattare anche i singoli appartamenti?", "Sì: su richiesta dei condòmini interveniamo anche negli alloggi privati, con preventivi dedicati.")],
    },
    {
        "slug": "ristoranti-bar", "nome": "Ristoranti, bar e pizzerie", "icona": "posate",
        "breve": "Pest control HACCP con controlli fuori orario e documenti pronti per i controlli ASL.",
        "seo_title": "Disinfestazione e pest control HACCP per ristoranti e bar",
        "seo_desc": "Pest control HACCP per ristoranti, bar, pizzerie e gelaterie: controlli periodici fuori orario, lampade cattura-insetti, piano di monitoraggio e documenti per l'ASL.",
        "h1": "Ristoranti e bar: <em>supera i controlli senza ansia</em>",
        "intro": "Una blatta in sala o un topo in magazzino possono costare la reputazione di un locale. Teniamo la situazione sotto controllo con un piano HACCP e passaggi fuori orario.",
        "problemi": ["Blatte attorno a frigoriferi, forni e lavastoviglie", "Topi in magazzino e nei locali rifiuti", "Mosche e moscerini in cucina", "Formiche e insetti delle derrate in dispensa", "Ispezioni ASL e verifiche dei clienti"],
        "soluzioni": ["Piano di monitoraggio HACCP con planimetria", "Gel e trattamenti senza chiudere il locale", "Lampade cattura-insetti a piastra collante", "Controlli fuori orario di apertura", "Pulizia di cappe, canne fumarie e degrassatori con lo stesso fornitore"],
        "documenti": ["Piano di monitoraggio", "Planimetria delle postazioni", "Schede di controllo", "Schede tecniche e di sicurezza dei prodotti"],
        "faq": [("Dovrò chiudere il locale?", "Quasi mai: usiamo gel, esche e trappole che non richiedono la chiusura, e lavoriamo prima dell'apertura o dopo la chiusura.")],
    },
    {
        "slug": "industria-alimentare", "nome": "Industria alimentare e magazzini", "icona": "fabbrica",
        "breve": "Programmi di difesa integrata, trend delle catture e supporto agli audit.",
        "seo_title": "Pest control per industrie alimentari, magazzini e logistica",
        "seo_desc": "Programmi di difesa integrata (IPM) per industrie alimentari, pastifici, panifici, magazzini e logistica: monitoraggio, trend, azioni correttive e supporto agli audit.",
        "h1": "Industria alimentare e magazzini: <em>controllo costante, audit tranquilli</em>",
        "intro": "Negli stabilimenti il pest control è parte del sistema qualità. Applichiamo la difesa integrata: prevenzione, monitoraggio, interventi mirati e dati per migliorare nel tempo.",
        "problemi": ["Roditori lungo il perimetro e nelle baie di carico", "Insetti delle derrate in silos, macchinari e materie prime", "Insetti volanti nelle zone di confezionamento", "Volatili nei capannoni", "Audit dei clienti e degli enti di certificazione"],
        "soluzioni": ["Valutazione dei rischi e piano di monitoraggio", "Postazioni interne ed esterne numerate", "Trappole a feromoni e lampade cattura-insetti", "Trend delle catture e azioni correttive", "Reti e dissuasori contro i volatili"],
        "documenti": ["Valutazione dei rischi", "Planimetrie aggiornate", "Schede di controllo e azioni correttive", "Report periodici e trend"],
        "faq": [("Supportate gli audit di certificazione?", "Sì: prepariamo la documentazione del pest control e, se serve, siamo presenti all'audit.")],
    },
    {
        "slug": "hotel-bnb", "nome": "Hotel, B&B e campeggi", "icona": "letto",
        "breve": "Cimici dei letti, zanzare, vespe: interventi discreti per non disturbare gli ospiti.",
        "seo_title": "Disinfestazione per hotel, B&B, campeggi e strutture ricettive",
        "seo_desc": "Disinfestazione per strutture ricettive: cimici dei letti, zanzare, vespe, roditori. Interventi riservati e programmati per non disturbare gli ospiti.",
        "h1": "Hotel, B&B e campeggi: <em>ospiti felici, recensioni pulite</em>",
        "intro": "Nel turismo ligure la stagione è breve e le recensioni contano. Interveniamo con discrezione e programmiamo i trattamenti per non disturbare gli ospiti.",
        "problemi": ["Cimici dei letti portate dai viaggiatori", "Zanzare in giardino, piscina e dehors", "Vespe e calabroni vicino a terrazze e bungalow", "Topi e blatte nella cucina della struttura", "Piccioni e gabbiani su terrazze e tetti"],
        "soluzioni": ["Ispezioni e trattamenti riservati delle camere", "Programma antizanzare stagionale", "Pest control HACCP per cucina e colazioni", "Formazione del personale ai controlli", "Interventi in orari concordati"],
        "documenti": ["Schede di intervento", "Piano HACCP per la cucina"],
        "faq": [("Potete intervenire in una sola camera?", "Sì: ispezioniamo la camera e quelle vicine, trattiamo dove serve e ti diciamo quando può essere riaffittata.")],
    },
    {
        "slug": "sanita-scuole", "nome": "Scuole, RSA e strutture sanitarie", "icona": "croce",
        "breve": "Prodotti e metodi adatti ad ambienti sensibili, con orari concordati.",
        "seo_title": "Disinfestazione per scuole, RSA, ambulatori e strutture sanitarie",
        "seo_desc": "Disinfestazione e derattizzazione per scuole, asili, RSA, ambulatori e strutture sanitarie: metodi adatti ad ambienti sensibili, orari concordati, documentazione completa.",
        "h1": "Scuole e strutture sanitarie: <em>massima attenzione</em>",
        "intro": "Dove ci sono bambini, anziani e pazienti scegliamo metodi a basso impatto e lavoriamo negli orari in cui gli ambienti sono vuoti.",
        "problemi": ["Topi nei locali cucina e nei depositi", "Blatte nei bagni e nelle mense", "Zanzare e vespe in cortili e giardini", "Processionaria sui pini dei cortili", "Piccioni sui tetti e nei cortili"],
        "soluzioni": ["Erogatori di sicurezza chiusi e fissati", "Gel ed esche al posto dei trattamenti spray", "Interventi in orari di chiusura o nei weekend", "Rimozione dei nidi di processionaria e di vespe", "Documenti per l'ente o la direzione sanitaria"],
        "documenti": ["Schede di intervento", "Schede di sicurezza dei prodotti", "Piano di monitoraggio"],
        "faq": [("Lavorate per enti pubblici?", "Sì, lavoriamo anche con enti pubblici e partecipiamo a gare e affidamenti.")],
    },
    {
        "slug": "negozi-uffici", "nome": "Negozi, uffici e aziende", "icona": "negozio",
        "breve": "Controlli programmati e interventi rapidi per non fermare la tua attività.",
        "seo_title": "Disinfestazione per negozi, uffici e aziende",
        "seo_desc": "Disinfestazione e derattizzazione per negozi, uffici, officine e aziende: controlli programmati, interventi rapidi su chiamata, documenti per il DVR e i clienti.",
        "h1": "Negozi, uffici e aziende: <em>l'attività non si ferma</em>",
        "intro": "Pianifichiamo i controlli e interveniamo in fretta quando serve, in orari che non disturbano clienti e dipendenti.",
        "problemi": ["Topi in archivi, magazzini e locali tecnici", "Insetti in spogliatoi e aree ristoro", "Piccioni su insegne e tettoie", "Zanzare nelle aree esterne"],
        "soluzioni": ["Contratti di controllo programmato", "Interventi su chiamata", "Sanificazione di uffici e spogliatoi", "Dissuasori per volatili su insegne e tettoie", "Gestione dei rifiuti aziendali con lo stesso fornitore"],
        "documenti": ["Schede di intervento", "Report periodici"],
        "faq": [("Avete anche altri servizi per le aziende?", "Sì: Servizi Ecologici si occupa anche di rifiuti, spurghi, pulizia di cappe e canalizzazioni dell'aria. Un solo fornitore per più esigenze.")],
    },
    {
        "slug": "porti-nautica", "nome": "Porti, marine e nautica", "icona": "barca",
        "breve": "Derattizzazione di banchine e imbarcazioni, volatili e insetti nei cantieri navali.",
        "seo_title": "Derattizzazione e disinfestazione per porti, marine e imbarcazioni",
        "seo_desc": "Derattizzazione di banchine, magazzini portuali e imbarcazioni, disinfestazione di yacht e cantieri navali, allontanamento di gabbiani in Liguria.",
        "h1": "Porti e nautica: <em>banchine e barche senza ospiti indesiderati</em>",
        "intro": "Lavoriamo da anni nei porti liguri con i servizi per la nautica. Ora portiamo anche il pest control a bordo e in banchina.",
        "problemi": ["Ratti su banchine, moli e magazzini", "Blatte a bordo di imbarcazioni e yacht", "Gabbiani e piccioni su capannoni e pontili", "Zanzare nelle marine in estate"],
        "soluzioni": ["Derattizzazione programmata delle aree portuali", "Disinfestazione a bordo con prodotti adatti", "Reti e dissuasori contro i gabbiani", "Programma antizanzare per le marine", "Svuotamento serbatoi e pulizia sentine con lo stesso fornitore"],
        "documenti": ["Schede di intervento", "Planimetria delle postazioni", "Report periodici"],
        "faq": [("Intervenite direttamente in porto?", "Sì, con mezzi e attrezzature adatti, coordinandoci con la marina o il cantiere.")],
    },
]

# ------------------------------------------------------------------ home
SEGNI = [
    ("Escrementi scuri tipo chicchi di riso", "topi-ratti"),
    ("Rumori nel controsoffitto di notte", "topi-ratti"),
    ("Insetti scuri che scappano alla luce", "blatte-scarafaggi"),
    ("File di piccoli insetti in cucina", "formiche"),
    ("Punture in fila al risveglio", "cimici-dei-letti"),
    ("Nido di carta sotto il tetto o in tapparella", "vespe-calabroni"),
    ("Punture di giorno in giardino", "zanzare"),
    ("Punture alle caviglie, il cane si gratta", "pulci-zecche"),
    ("Nidi bianchi tipo ovatta sui pini", "processionaria"),
    ("Guano su terrazzi e davanzali", "piccioni-gabbiani"),
    ("Farfalline o ragnatele nella farina", "insetti-derrate"),
    ("Insetti argentati in bagno", "pesciolini-argento"),
    ("Tante mosche vicino ai rifiuti", "mosche"),
]

PIANI = [
    {"nome": "Casa Protetta", "per": "Privati", "evidenza": False,
     "voci": ["Sopralluogo gratuito", "Trattamento mirato sull'infestante", "Erogatori sicuri per bambini e animali", "Consigli scritti di prevenzione", "Scheda di intervento"],
     "nota": "La soluzione per un problema preciso, risolto alla radice."},
    {"nome": "Condominio Sereno", "per": "Amministratori", "evidenza": True,
     "voci": ["Derattizzazione + disinfestazione delle parti comuni", "3 passaggi programmati nell'anno", "Avvisi per la bacheca", "Interventi extra su chiamata", "Report per l'assemblea"],
     "nota": "Un unico contratto annuale, prezzi chiari e documenti in ordine."},
    {"nome": "HACCP Ristorazione", "per": "Ristoranti, bar, mense", "evidenza": False,
     "voci": ["Piano di monitoraggio e planimetria", "Postazioni per roditori e striscianti", "Lampade cattura-insetti", "Controlli periodici fuori orario", "Cartella documenti per l'ASL"],
     "nota": "Tutto ciò che serve per i controlli ufficiali, sempre aggiornato."},
    {"nome": "Industria & Logistica", "per": "Stabilimenti e magazzini", "evidenza": False,
     "voci": ["Valutazione dei rischi", "Postazioni interne ed esterne", "Trappole a feromoni", "Trend e azioni correttive", "Supporto agli audit"],
     "nota": "Difesa integrata con dati misurabili nel tempo."},
    {"nome": "Estate senza Zanzare", "per": "Giardini e strutture turistiche", "evidenza": False,
     "voci": ["Mappatura dei focolai", "Larvicida nei tombini da aprile a ottobre", "Adulticida nei periodi di picco", "Trattamenti prima di eventi", "Promemoria prima dei passaggi"],
     "nota": "Un calendario di interventi da primavera all'autunno."},
    {"nome": "Verde Sicuro", "per": "Ville, condomini, scuole", "evidenza": False,
     "voci": ["Controllo processionaria sui pini", "Rimozione nidi in inverno", "Trattamento preventivo in autunno", "Controllo nidi di vespe in primavera", "Trappole a collare"],
     "nota": "Pini e giardini sicuri per bambini e animali tutto l'anno."},
]

FAQ_HOME = [
    ("Il preventivo è gratuito?", "Sì, il preventivo e il sopralluogo sono gratuiti e senza impegno. Per vespe, calabroni e insetti puoi anche mandarci una foto su WhatsApp."),
    ("I prodotti sono sicuri per bambini e animali?", "Usiamo solo prodotti autorizzati per l'uso professionale e li applichiamo in modo mirato: gel nei punti nascosti, esche in erogatori chiusi a chiave. Ti diciamo sempre come comportarti dopo il trattamento."),
    ("Quanto costa una disinfestazione?", "Dipende dall'infestante, dalla superficie e dal numero di passaggi. Dopo il sopralluogo ricevi un preventivo scritto con tutto incluso, senza sorprese."),
    ("In quanto tempo intervenite?", "Per vespe e calabroni vicini alle persone e per le attività alimentari diamo la priorità. Per gli altri interventi concordiamo con te il primo giorno utile."),
    ("Rilasciate documenti per l'ASL?", "Sì: ogni intervento ha la sua scheda, e per le attività alimentari prepariamo piano di monitoraggio, planimetria e report periodici per il piano HACCP."),
    ("In che zone lavorate?", "In tutta la Liguria, nelle province di Savona, Imperia, Genova e La Spezia, e nel basso Piemonte. Partiamo da Finalborgo (Finale Ligure)."),
    ("Basta un solo intervento?", "Per alcuni insetti sì, per topi, blatte e cimici di solito servono più passaggi: le uova e i piccoli vanno colpiti nel tempo. Te lo diciamo chiaramente nel preventivo."),
    ("Che cos'è la difesa integrata (IPM)?", "È un metodo che mette al primo posto prevenzione e monitoraggio, e usa i prodotti solo dove e quando servono. Meno chimica e risultati più duraturi."),
]

ZONE = ["Finale Ligure", "Savona", "Albenga", "Loano", "Pietra Ligure", "Alassio", "Spotorno", "Noli", "Varazze", "Vado Ligure",
        "Andora", "Imperia", "Sanremo", "Ventimiglia", "Taggia", "Genova", "Cairo Montenotte", "La Spezia", "Basso Piemonte"]

GUIDA = [
    ("In cucina", [
        "Conserva cibo, cereali e croccantini in contenitori ermetici",
        "Non lasciare stoviglie sporche e briciole durante la notte",
        "Svuota spesso il bidone dell'organico e lavalo",
        "Controlla dietro frigorifero, forno e lavastoviglie: sono i rifugi preferiti delle blatte",
        "Ripara subito le perdite d'acqua sotto il lavello",
    ]),
    ("In bagno e in cantina", [
        "Arieggia e deumidifica: l'umidità attira pesciolini d'argento, blatte e millepiedi",
        "Metti tappi o retine sugli scarichi poco usati",
        "Non accumulare scatoloni e vecchi giornali: sono rifugi e cibo per molti insetti",
        "Sigilla i fori attorno a tubi e cavi che arrivano dall'esterno",
    ]),
    ("In giardino e sul terrazzo", [
        "Svuota ogni settimana sottovasi, secchi e tutto ciò che raccoglie acqua",
        "Pulisci grondaie e caditoie",
        "Tieni l'erba bassa e la legna lontana dai muri di casa",
        "Raccogli la frutta caduta e non lasciare cibo per gli animali all'aperto",
        "A fine inverno controlla tapparelle, sottotetti e pini",
    ]),
    ("Cosa non fare mai", [
        "Spargere veleno per topi senza erogatori chiusi: è pericoloso per bambini, cani e gatti",
        "Bruciare o bagnare un nido di vespe o calabroni",
        "Toccare nidi o bruchi di processionaria",
        "Usare insetticidi spray in grandi quantità in ambienti chiusi",
        "Dare da mangiare a piccioni e gabbiani",
    ]),
]

# ------------------------------------------------------------------ pacchetti multiservizio
# Riferimenti normativi indicativi: da far verificare al consulente prima della pubblicazione.
LEGGI = {
    "852": ("Reg. CE 852/2004", "Igiene dei prodotti alimentari: obbligo di controllo degli infestanti e di impianti di ventilazione puliti e manutenuti (piano HACCP)."),
    "acque": ("D.Lgs. 18/2023", "Qualità delle acque destinate al consumo umano: controlli e analisi dell'acqua erogata ai clienti."),
    "legionella": ("Linee guida Legionellosi 2015", "Linee guida nazionali per la prevenzione e il controllo della legionellosi (Conferenza Stato-Regioni 7/5/2015): valutazione del rischio in strutture ricettive."),
    "aria": ("Accordo Stato-Regioni 7/2/2013", "Procedura per la valutazione e la gestione dei rischi legati all'igiene degli impianti di trattamento dell'aria."),
    "81": ("D.Lgs. 81/2008", "Sicurezza nei luoghi di lavoro: aerazione e salubrità degli ambienti per i dipendenti."),
    "antincendio": ("D.M. 3 settembre 2021", "Gestione della sicurezza antincendio: pulizia e manutenzione di cappe, condotti e impianti che possono causare incendi."),
    "uni10683": ("Norma UNI 10683", "Generatori di calore a legna e pellet: controllo e pulizia periodica di canne fumarie e camini."),
    "152": ("D.Lgs. 152/2006", "Testo unico ambientale: gestione corretta di rifiuti, fanghi, oli e scarichi (fosse, degrassatori)."),
    "rentri": ("D.M. 59/2023 (RENTRI)", "Registro elettronico nazionale per la tracciabilità dei rifiuti e formulario digitale."),
    "biocidi": ("Reg. UE 528/2012", "Uso di biocidi e presidi autorizzati negli interventi di disinfestazione e derattizzazione."),
    "amianto": ("D.M. 6 settembre 1994", "Censimento, valutazione e gestione dei materiali contenenti amianto negli edifici."),
}

PACCHETTI_MULTI = [
    {"slug": "pizzeria-ristorante", "nome": "Pizzeria & Ristorante", "icona": "posate", "evidenza": True,
     "per": "Pizzerie, ristoranti, trattorie, kebab e rosticcerie",
     "servizi": ["Derattizzazione con postazioni numerate", "Disinfestazione da blatte e insetti (pest control HACCP)", "Lampade cattura-insetti in cucina",
                 "Pulizia della cappa e della canalizzazione di aspirazione", "Pulizia della canna fumaria del forno a legna, con prove di tenuta e certificazione su richiesta", "Pulizia e svuotamento del degrassatore",
                 "Analisi dell'acqua potabile"],
     "leggi": ["852", "acque", "antincendio", "uni10683", "152", "biocidi"],
     "ricevi": "Cartella unica con piano HACCP infestanti, certificati di pulizia di cappa e canna fumaria, rapporto di analisi dell'acqua e formulari dei rifiuti.",
     "perche": "Un forno a legna e una cappa sporca sono tra le prime cause di incendio nei locali: con un solo fornitore hai tutte le scadenze sotto controllo."},
    {"slug": "hotel-bnb", "nome": "Hotel & B&B", "icona": "letto", "evidenza": True,
     "per": "Hotel, residence, B&B, affittacamere e case vacanza",
     "servizi": ["Pest control HACCP per cucina e sala colazioni", "Ispezioni e trattamenti riservati contro le cimici dei letti", "Programma antizanzare per giardino, piscina e terrazze",
                 "Rimozione nidi di vespe e calabroni", "Igienizzazione delle canalizzazioni dell'aria e dei condizionatori", "Analisi dell'acqua potabile e controllo del rischio Legionella", "Sanificazione delle tubazioni contro la Legionella", "Analisi e pulizia dell'acqua della piscina",
                 "Pulizia cappa e canne fumarie di cucina e camini", "Spurgo di fosse biologiche e degrassatori"],
     "leggi": ["852", "acque", "legionella", "aria", "antincendio", "152"],
     "ricevi": "Calendario annuale degli interventi pensato sulla stagione turistica, con documenti pronti per ASL, ispezioni e catene alberghiere.",
     "perche": "Ospiti senza punture e senza sorprese, impianti dell'aria puliti e acqua controllata: le recensioni ringraziano."},
    {"slug": "bar-pasticceria", "nome": "Bar, Gelateria & Pasticceria", "icona": "tazza", "evidenza": False,
     "per": "Bar, caffetterie, gelaterie, pasticcerie, panifici",
     "servizi": ["Derattizzazione e disinfestazione HACCP", "Trappole a feromoni per tarme delle farine", "Lampade cattura-insetti",
                 "Pulizia della cappa del laboratorio", "Pulizia del degrassatore", "Analisi dell'acqua potabile (anche per macchine del caffè e ghiaccio)"],
     "leggi": ["852", "acque", "antincendio", "152", "biocidi"],
     "ricevi": "Planimetria delle postazioni, schede di controllo, rapporto di analisi dell'acqua e certificati di pulizia.",
     "perche": "Farine, zuccheri e dolci attirano insetti e roditori: il controllo costante evita merce da buttare e contestazioni."},
    {"slug": "condominio-completo", "nome": "Condominio Completo", "icona": "palazzo", "evidenza": False,
     "per": "Amministratori di condominio e supercondomini",
     "servizi": ["Derattizzazione e disinfestazione delle parti comuni (3 passaggi)", "Spurgo delle colonne di scarico e dei pozzetti", "Svuotamento della fossa biologica",
                 "Videoispezione della rete fognaria e relining delle tubazioni senza demolizioni", "Allontanamento di piccioni e gabbiani", "Pulizia delle canne fumarie condominiali",
                 "Pulizia dei serbatoi di acqua potabile e analisi dell'acqua di serbatoi e autoclavi", "Censimento dei materiali in amianto"],
     "leggi": ["152", "acque", "uni10683", "amianto", "biocidi"],
     "ricevi": "Un unico contratto annuale con un report da presentare in assemblea e tutti i formulari dei rifiuti.",
     "perche": "Un solo referente per tutte le manutenzioni igieniche del palazzo, prezzi chiari e meno chiamate dei condòmini."},
    {"slug": "industria-alimentare", "nome": "Industria Alimentare", "icona": "fabbrica", "evidenza": False,
     "per": "Stabilimenti alimentari, pastifici, oleifici, cantine, magazzini",
     "servizi": ["Programma di difesa integrata (IPM) con trend e azioni correttive", "Monitoraggio degli insetti delle derrate con feromoni", "Reti e dissuasori per volatili nei capannoni",
                 "Pulizia delle canalizzazioni dell'aria e delle UTA", "Analisi delle acque di processo e potabili", "Ritiro dei rifiuti con FIR digitale RENTRI",
                 "Pulizia e bonifica di cisterne e serbatoi"],
     "leggi": ["852", "acque", "aria", "81", "152", "rentri"],
     "ricevi": "Documentazione completa per HACCP, audit dei clienti e certificazioni, aggiornata a ogni controllo.",
     "perche": "Meno non conformità negli audit e un unico fornitore che conosce il tuo stabilimento."},
    {"slug": "scuole-rsa-mense", "nome": "Scuole, RSA & Mense", "icona": "croce", "evidenza": False,
     "per": "Scuole, asili, RSA, comunità, mense aziendali",
     "servizi": ["Derattizzazione e disinfestazione con metodi a basso impatto", "Rimozione di nidi di processionaria e di vespe nei cortili", "Pulizia della cappa della cucina",
                 "Pulizia delle canalizzazioni dell'aria", "Analisi dell'acqua potabile", "Sanificazione degli ambienti"],
     "leggi": ["852", "acque", "aria", "81", "antincendio"],
     "ricevi": "Interventi in orari di chiusura e documenti per la direzione o l'ente, anche per affidamenti pubblici.",
     "perche": "Ambienti sicuri per bambini, anziani e personale, con la massima attenzione ai prodotti usati."},
    {"slug": "campeggi-stabilimenti", "nome": "Campeggi & Stabilimenti Balneari", "icona": "ombrellone", "evidenza": False,
     "per": "Campeggi, villaggi turistici, stabilimenti balneari, chioschi",
     "servizi": ["Programma antizanzare stagionale", "Rimozione nidi di vespe e calabroni", "Derattizzazione di aree esterne e depositi",
                 "Pest control HACCP per bar e ristorante", "Svuotamento di fosse biologiche e bagni chimici", "Analisi dell'acqua di docce e fontanelle", "Analisi e pulizia dell'acqua delle piscine",
                 "Ritiro dei rifiuti di fine stagione"],
     "leggi": ["acque", "852", "152", "legionella", "biocidi"],
     "ricevi": "Un calendario da aprile a ottobre, con interventi programmati prima dell'apertura e durante l'alta stagione.",
     "perche": "Clienti in vacanza senza zanzare e vespe, e servizi igienici sempre a posto."},
    {"slug": "agriturismo-casa-vacanze", "nome": "Agriturismo & Villa", "icona": "casa", "evidenza": False,
     "per": "Agriturismi, ville, case di campagna, case vacanza",
     "servizi": ["Derattizzazione di casa, rustici e magazzini", "Controllo della processionaria sui pini", "Programma antizanzare per giardino e piscina",
                 "Pulizia di canne fumarie, camini e stufe", "Svuotamento della fossa biologica", "Analisi dell'acqua di pozzo o sorgente", "Analisi e pulizia dell'acqua della piscina"],
     "leggi": ["acque", "uni10683", "152", "852", "biocidi"],
     "ricevi": "Un piano annuale su misura per la struttura, con promemoria delle scadenze.",
     "perche": "Chi usa acqua di pozzo e scarica in fossa ha obblighi in più: li seguiamo noi."},
    {"slug": "aziende-officine", "nome": "Aziende & Officine", "icona": "negozio", "evidenza": False,
     "per": "Officine, artigiani, uffici, negozi, capannoni",
     "servizi": ["Derattizzazione programmata di magazzini e archivi", "Disinfestazione di spogliatoi e aree ristoro", "Pulizia delle canalizzazioni dell'aria e dei condizionatori",
                 "Ritiro programmato dei rifiuti (oli, filtri, imballaggi) con FIR digitale", "Pulizia e dismissione di cisterne di gasolio", "Sanificazione degli ambienti"],
     "leggi": ["81", "aria", "152", "rentri", "biocidi"],
     "ricevi": "Documenti utili per il DVR, i registri dei rifiuti e i controlli degli enti.",
     "perche": "Ambienti di lavoro salubri e rifiuti in regola, senza dover rincorrere più fornitori."},
    {"slug": "porti-nautica", "nome": "Marine & Nautica", "icona": "barca", "evidenza": False,
     "per": "Porti turistici, cantieri navali, yacht e charter",
     "servizi": ["Derattizzazione di banchine e magazzini", "Disinfestazione a bordo", "Reti e dissuasori contro i gabbiani",
                 "Svuotamento di serbatoi di acque nere e sentine", "Pulizia delle casse gasolio e gas-free", "Pulizia degli impianti aria di bordo"],
     "leggi": ["152", "rentri", "aria", "biocidi"],
     "ricevi": "Interventi coordinati con la marina e formulari per ogni rifiuto di bordo.",
     "perche": "Barche e banchine pulite, servizi direttamente in porto."},
]
